### ISSUE TITLE
Decoder returns always null on AudioBuffer

### ISSUE THREAD

**Issue by nhh** [ImagicTheCat/libopusjs#1]
Hi!

First of all, thank you for this repository and all the work you've done! Second, i am fairly new to "low-level" programming with byte arrays, buffers and stuff. So it is most likely my fault, and i appreciate a tip to the right direction.

Context: What i try to approach:

I want to use libopusjs to encode browser captures voice, send this as binary data over a websocket to another computer which decoded the data and plays it back.

This is what i got so far:

Client Side:

```javascript

libopus.onload = async function() {
    var enc = new libopus.Encoder(1, 48000, 24000, 40, false);
    var dec = new libopus.Decoder(1,48000);

    const stream = await navigator.mediaDevices.getUserMedia({ audio: true, video: false });
    const context = new AudioContext();

    const microphone = context.createMediaStreamSource(stream);
    const processor = context.createScriptProcessor(4096, 1, 1);
    const bufferSource = context.createBufferSource();

    var voiceBuffer = null;

    const host = location.origin.replace(/^http/, 'ws');
    const ws = new WebSocket(host);

    ws.binaryType = 'arraybuffer';

    ws.onmessage = message => {
        dec.input(message.data);
        voiceBuffer = dec.output();
    };

    processor.onaudioprocess = e => {
        enc.input(e.inputBuffer);
        ws.send(enc.output());
    };

    bufferSource.buffer = voiceBuffer;
    bufferSource.start(0);
    bufferSource.connect(context.destination);

    microphone.connect(processor);
    processor.connect(context.destination);
    //microphone.connect(context.destination) // If i connect the microphone directly i am hearing myself

};

```

Server Side: Simple echo of the incoming data atm. (Verified its binary, and also an AudioBuffer)

![Bildschirmfoto 2020-03-28 um 16 15 46](https://user-images.githubusercontent.com/13472382/77826414-63246880-710f-11ea-9e62-9bd6055f4e1a.png)

My guess is, that the Audiobuffer i am encoding with libopusjs and send over the network is not correctly decoded, since the `dec.output()` is always null.

I would love to get some pointers a good read on webaudio stuff or libopusjs docs where i can read what the `dec.input()` needs. Or more fundamentally, is a `AudioBuffer` suited for the usage with libopusjs?

Thank you!

**Comment by ImagicTheCat** [comment]
You can see an usage example at https://github.com/ImagicTheCat/vRP/blob/master/vrp/gui/AudioEngine.js (I created this library for this project). 

You must read the output of the encoder or decoder with a loop until there is nothing to read, because each packet/samples can produce X number of samples/packets at each step, where X can be 0 or more. It's a stream API.

**Comment by nhh** [comment]
Wow, what a treasure! Thanks for the link.

So i guess the `while(data)` does the trick. Thanks again!

Btw, big kudos for that library!
