### ISSUE TITLE
_free not exported by emscripten

### ISSUE THREAD

**Issue by chrbsg** [ImagicTheCat/libopusjs#2]
libopusjs fails with recent emscipten (2.0.17) which does not export _free. This appears to be a change (from generated code `"free() called but not included in the build - add '_free' to EXPORTED_FUNCTIONS"`).

So build.sh should be something like:

```
em++ api.cpp -Iopus/include -Lopus/.libs -lopus --pre-js preapi.js \
  --post-js api.js -s EXPORTED_FUNCTIONS='["_free"]' $@ -o libopus.js
```

**Comment by ImagicTheCat** [comment]
I'm not particularly maintaining the project, are you interested in testing and making a pull request ?

**Comment by ImagicTheCat** [comment]
https://github.com/ImagicTheCat/libopusjs/commit/8d8ad807cece9132b8b985d6a021b7055e12cb8c
